version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chatapp
    ports:
      - "5440:5432"
    volumes:
      - ./database/chatapp_pgdata:/var/lib/postgresql/data
volumes:
  db_data:
